[phases.setup]
nixPkgs = ["python310"]

[phases.install]
cmds = ["cd backend && python -m pip install -r requirements.txt"]

[phases.build]
cmds = ["cd backend && python manage.py collectstatic --noinput"]

[start]
cmd = "cd backend && gunicorn config.wsgi --bind 0.0.0.0:$PORT"